# Generated by Django 3.2.4 on 2021-07-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0002_auto_20210703_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=15),
        ),
    ]
