# Generated by Django 3.2.4 on 2021-07-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0003_alter_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='suscrito',
            field=models.BooleanField(default=False),
        ),
    ]
