# Generated by Django 3.2.4 on 2021-07-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0004_usuario_suscrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.FileField(upload_to=''),
        ),
    ]
