# Generated by Django 3.2.4 on 2021-07-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0005_alter_producto_foto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promocion',
        ),
    ]
