# Generated by Django 3.2.4 on 2021-07-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0007_auto_20210703_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemventa',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
