# Generated by Django 3.2.4 on 2021-07-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0008_alter_itemventa_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='comentario',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='documento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
