# Generated by Django 3.2.4 on 2021-07-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0012_auto_20210703_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemventa',
            name='descuento',
        ),
    ]
