# Generated by Django 3.2.4 on 2021-07-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0013_remove_itemventa_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='token',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
