# Generated by Django 3.2.4 on 2021-07-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0015_auto_20210704_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Percusión', 'Percusión'), ('Accesorios varios', 'Accesorios varios'), ('Instrumentos de Cuerdas', 'Instrumentos de Cuerdas'), ('Amplificadores', 'Amplificadores')], max_length=50),
        ),
    ]
