# Generated by Django 3.2.4 on 2021-07-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0016_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Amplificadores', 'Amplificadores'), ('Percusión', 'Percusión'), ('Accesorios varios', 'Accesorios varios'), ('Instrumentos de Cuerdas', 'Instrumentos de Cuerdas')], max_length=50),
        ),
    ]
