# Generated by Django 3.2.4 on 2021-07-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0017_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Accesorios varios', 'Accesorios varios'), ('Amplificadores', 'Amplificadores'), ('Percusión', 'Percusión'), ('Instrumentos de Cuerdas', 'Instrumentos de Cuerdas')], max_length=50),
        ),
    ]
