# Generated by Django 3.2.4 on 2021-07-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0018_auto_20210704_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='estado',
            field=models.CharField(choices=[('En Carrito', 'En Carrito'), ('Pago Pendiente', 'Pago Pendiente'), ('Pagado', 'Pagado'), ('En Camino', 'En Camino'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Percusión', 'Percusión'), ('Instrumentos de Cuerdas', 'Instrumentos de Cuerdas'), ('Accesorios varios', 'Accesorios varios'), ('Amplificadores', 'Amplificadores')], max_length=50),
        ),
    ]
