# Generated by Django 3.2.4 on 2021-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0019_auto_20210704_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Percusión', 'Percusión'), ('Amplificadores', 'Amplificadores'), ('Instrumentos de Cuerdas', 'Instrumentos de Cuerdas'), ('Accesorios varios', 'Accesorios varios')], max_length=50),
        ),
    ]
