# Generated by Django 3.2.4 on 2021-07-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0020_auto_20210704_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Instrumentos de Cuerdas', 'Instrumentos de Cuerdas'), ('Percusión', 'Percusión'), ('Amplificadores', 'Amplificadores'), ('Accesorios varios', 'Accesorios varios')], max_length=50),
        ),
    ]
