# Generated by Django 3.2.4 on 2021-07-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0022_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Accesorios varios', 'Accesorios varios'), ('Percusión', 'Percusión'), ('Amplificadores', 'Amplificadores'), ('Instrumentos de Cuerdas', 'Instrumentos de Cuerdas')], max_length=50),
        ),
    ]
