# Generated by Django 3.2.4 on 2021-07-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0023_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Instrumentos de Cuerdas', 'Instrumentos de Cuerdas'), ('Accesorios varios', 'Accesorios varios'), ('Amplificadores', 'Amplificadores'), ('Percusión', 'Percusión')], max_length=50),
        ),
    ]
