# Generated by Django 3.2.4 on 2021-07-05 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicpro', '0025_auto_20210705_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='encargado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicpro.usuario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Percusión', 'Percusión'), ('Instrumentos de Cuerdas', 'Instrumentos de Cuerdas'), ('Accesorios varios', 'Accesorios varios'), ('Amplificadores', 'Amplificadores')], max_length=50),
        ),
    ]
